version: "3.9"

services:
  fakeserver:
    image: apisguru/graphql-faker
    container_name: graphql-fakeserver
    command: "fake.graphql"
    ports:
      - "9002:9002"
    volumes:
      - ./fakeserver:/workdir

  products-db:
    image: mongo:6.0-jammy
    container_name: products-db-mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - products-ms-data:/data/db
    env_file:
      - ./env/mongo.env

  products-api:
    build: .
    container_name: products-ms-api
    ports:
      - "8002:8000"
    volumes:
      - ./app/:/microservice/app/
    env_file:
      - ./env/api.env
    depends_on:
      - products-db

volumes:
  products-ms-data:
