"""allow nulls

Revision ID: fd58859b0819
Revises: ebc6ee5e3e7d
Create Date: 2023-03-10 07:01:42.247986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd58859b0819'
down_revision = 'ebc6ee5e3e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'schedule_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'delivery_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'delivery_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'schedule_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
