# Generated by Django 4.1.7 on 2023-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_schedule_app_schedul_created_b58d6e_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
